//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace FinalProject.connection {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="connection.connectionSoap")]
    public interface connectionSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExecuteScalar", ReplyAction="*")]
        System.IAsyncResult BeginExecuteScalar(FinalProject.connection.ExecuteScalarRequest request, System.AsyncCallback callback, object asyncState);
        
        FinalProject.connection.ExecuteScalarResponse EndExecuteScalar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExecuteNonQuery", ReplyAction="*")]
        System.IAsyncResult BeginExecuteNonQuery(FinalProject.connection.ExecuteNonQueryRequest request, System.AsyncCallback callback, object asyncState);
        
        FinalProject.connection.ExecuteNonQueryResponse EndExecuteNonQuery(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteScalarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteScalar", Namespace="http://tempuri.org/", Order=0)]
        public FinalProject.connection.ExecuteScalarRequestBody Body;
        
        public ExecuteScalarRequest() {
        }
        
        public ExecuteScalarRequest(FinalProject.connection.ExecuteScalarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteScalarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sql;
        
        public ExecuteScalarRequestBody() {
        }
        
        public ExecuteScalarRequestBody(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteScalarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteScalarResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinalProject.connection.ExecuteScalarResponseBody Body;
        
        public ExecuteScalarResponse() {
        }
        
        public ExecuteScalarResponse(FinalProject.connection.ExecuteScalarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteScalarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteScalarResult;
        
        public ExecuteScalarResponseBody() {
        }
        
        public ExecuteScalarResponseBody(string ExecuteScalarResult) {
            this.ExecuteScalarResult = ExecuteScalarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteNonQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteNonQuery", Namespace="http://tempuri.org/", Order=0)]
        public FinalProject.connection.ExecuteNonQueryRequestBody Body;
        
        public ExecuteNonQueryRequest() {
        }
        
        public ExecuteNonQueryRequest(FinalProject.connection.ExecuteNonQueryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteNonQueryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sql;
        
        public ExecuteNonQueryRequestBody() {
        }
        
        public ExecuteNonQueryRequestBody(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteNonQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteNonQueryResponse", Namespace="http://tempuri.org/", Order=0)]
        public FinalProject.connection.ExecuteNonQueryResponseBody Body;
        
        public ExecuteNonQueryResponse() {
        }
        
        public ExecuteNonQueryResponse(FinalProject.connection.ExecuteNonQueryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExecuteNonQueryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExecuteNonQueryResult;
        
        public ExecuteNonQueryResponseBody() {
        }
        
        public ExecuteNonQueryResponseBody(string ExecuteNonQueryResult) {
            this.ExecuteNonQueryResult = ExecuteNonQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface connectionSoapChannel : FinalProject.connection.connectionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteScalarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteScalarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class connectionSoapClient : System.ServiceModel.ClientBase<FinalProject.connection.connectionSoap>, FinalProject.connection.connectionSoap {
        
        private BeginOperationDelegate onBeginExecuteScalarDelegate;
        
        private EndOperationDelegate onEndExecuteScalarDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteScalarCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecuteNonQueryDelegate;
        
        private EndOperationDelegate onEndExecuteNonQueryDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteNonQueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public connectionSoapClient() {
        }
        
        public connectionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public connectionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public connectionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public connectionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ExecuteScalarCompletedEventArgs> ExecuteScalarCompleted;
        
        public event System.EventHandler<ExecuteNonQueryCompletedEventArgs> ExecuteNonQueryCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FinalProject.connection.connectionSoap.BeginExecuteScalar(FinalProject.connection.ExecuteScalarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteScalar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginExecuteScalar(string sql, System.AsyncCallback callback, object asyncState) {
            FinalProject.connection.ExecuteScalarRequest inValue = new FinalProject.connection.ExecuteScalarRequest();
            inValue.Body = new FinalProject.connection.ExecuteScalarRequestBody();
            inValue.Body.sql = sql;
            return ((FinalProject.connection.connectionSoap)(this)).BeginExecuteScalar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalProject.connection.ExecuteScalarResponse FinalProject.connection.connectionSoap.EndExecuteScalar(System.IAsyncResult result) {
            return base.Channel.EndExecuteScalar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndExecuteScalar(System.IAsyncResult result) {
            FinalProject.connection.ExecuteScalarResponse retVal = ((FinalProject.connection.connectionSoap)(this)).EndExecuteScalar(result);
            return retVal.Body.ExecuteScalarResult;
        }
        
        private System.IAsyncResult OnBeginExecuteScalar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sql = ((string)(inValues[0]));
            return this.BeginExecuteScalar(sql, callback, asyncState);
        }
        
        private object[] OnEndExecuteScalar(System.IAsyncResult result) {
            string retVal = this.EndExecuteScalar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteScalarCompleted(object state) {
            if ((this.ExecuteScalarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteScalarCompleted(this, new ExecuteScalarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteScalarAsync(string sql) {
            this.ExecuteScalarAsync(sql, null);
        }
        
        public void ExecuteScalarAsync(string sql, object userState) {
            if ((this.onBeginExecuteScalarDelegate == null)) {
                this.onBeginExecuteScalarDelegate = new BeginOperationDelegate(this.OnBeginExecuteScalar);
            }
            if ((this.onEndExecuteScalarDelegate == null)) {
                this.onEndExecuteScalarDelegate = new EndOperationDelegate(this.OnEndExecuteScalar);
            }
            if ((this.onExecuteScalarCompletedDelegate == null)) {
                this.onExecuteScalarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteScalarCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteScalarDelegate, new object[] {
                        sql}, this.onEndExecuteScalarDelegate, this.onExecuteScalarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FinalProject.connection.connectionSoap.BeginExecuteNonQuery(FinalProject.connection.ExecuteNonQueryRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteNonQuery(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginExecuteNonQuery(string sql, System.AsyncCallback callback, object asyncState) {
            FinalProject.connection.ExecuteNonQueryRequest inValue = new FinalProject.connection.ExecuteNonQueryRequest();
            inValue.Body = new FinalProject.connection.ExecuteNonQueryRequestBody();
            inValue.Body.sql = sql;
            return ((FinalProject.connection.connectionSoap)(this)).BeginExecuteNonQuery(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FinalProject.connection.ExecuteNonQueryResponse FinalProject.connection.connectionSoap.EndExecuteNonQuery(System.IAsyncResult result) {
            return base.Channel.EndExecuteNonQuery(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndExecuteNonQuery(System.IAsyncResult result) {
            FinalProject.connection.ExecuteNonQueryResponse retVal = ((FinalProject.connection.connectionSoap)(this)).EndExecuteNonQuery(result);
            return retVal.Body.ExecuteNonQueryResult;
        }
        
        private System.IAsyncResult OnBeginExecuteNonQuery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sql = ((string)(inValues[0]));
            return this.BeginExecuteNonQuery(sql, callback, asyncState);
        }
        
        private object[] OnEndExecuteNonQuery(System.IAsyncResult result) {
            string retVal = this.EndExecuteNonQuery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteNonQueryCompleted(object state) {
            if ((this.ExecuteNonQueryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteNonQueryCompleted(this, new ExecuteNonQueryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteNonQueryAsync(string sql) {
            this.ExecuteNonQueryAsync(sql, null);
        }
        
        public void ExecuteNonQueryAsync(string sql, object userState) {
            if ((this.onBeginExecuteNonQueryDelegate == null)) {
                this.onBeginExecuteNonQueryDelegate = new BeginOperationDelegate(this.OnBeginExecuteNonQuery);
            }
            if ((this.onEndExecuteNonQueryDelegate == null)) {
                this.onEndExecuteNonQueryDelegate = new EndOperationDelegate(this.OnEndExecuteNonQuery);
            }
            if ((this.onExecuteNonQueryCompletedDelegate == null)) {
                this.onExecuteNonQueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteNonQueryCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteNonQueryDelegate, new object[] {
                        sql}, this.onEndExecuteNonQueryDelegate, this.onExecuteNonQueryCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FinalProject.connection.connectionSoap CreateChannel() {
            return new connectionSoapClientChannel(this);
        }
        
        private class connectionSoapClientChannel : ChannelBase<FinalProject.connection.connectionSoap>, FinalProject.connection.connectionSoap {
            
            public connectionSoapClientChannel(System.ServiceModel.ClientBase<FinalProject.connection.connectionSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginExecuteScalar(FinalProject.connection.ExecuteScalarRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteScalar", _args, callback, asyncState);
                return _result;
            }
            
            public FinalProject.connection.ExecuteScalarResponse EndExecuteScalar(System.IAsyncResult result) {
                object[] _args = new object[0];
                FinalProject.connection.ExecuteScalarResponse _result = ((FinalProject.connection.ExecuteScalarResponse)(base.EndInvoke("ExecuteScalar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginExecuteNonQuery(FinalProject.connection.ExecuteNonQueryRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ExecuteNonQuery", _args, callback, asyncState);
                return _result;
            }
            
            public FinalProject.connection.ExecuteNonQueryResponse EndExecuteNonQuery(System.IAsyncResult result) {
                object[] _args = new object[0];
                FinalProject.connection.ExecuteNonQueryResponse _result = ((FinalProject.connection.ExecuteNonQueryResponse)(base.EndInvoke("ExecuteNonQuery", _args, result)));
                return _result;
            }
        }
    }
}
